gen stateabbrev = "."
replace stateabbrev = "AL" if statefip == 1
replace stateabbrev = "AK" if statefip == 2
replace stateabbrev = "AZ" if statefip == 4
replace stateabbrev = "AR" if statefip == 5
replace stateabbrev = "CA" if statefip == 6
replace stateabbrev = "CO" if statefip == 8
replace stateabbrev = "CT" if statefip == 9
replace stateabbrev = "DE" if statefip == 10
replace stateabbrev = "DC" if statefip == 11
replace stateabbrev = "FL" if statefip == 12
replace stateabbrev = "GA" if statefip == 13
replace stateabbrev = "HI" if statefip == 15
replace stateabbrev = "ID" if statefip == 16
replace stateabbrev = "IL" if statefip == 17
replace stateabbrev = "IN" if statefip == 18
replace stateabbrev = "IA" if statefip == 19
replace stateabbrev = "KS" if statefip == 20
replace stateabbrev = "KY" if statefip == 21
replace stateabbrev = "LA" if statefip == 22
replace stateabbrev = "ME" if statefip == 23
replace stateabbrev = "MD" if statefip == 24
replace stateabbrev = "MA" if statefip == 25
replace stateabbrev = "MI" if statefip == 26
replace stateabbrev = "MN" if statefip == 27
replace stateabbrev = "MS" if statefip == 28
replace stateabbrev = "MO" if statefip == 29
replace stateabbrev = "MT" if statefip == 30
replace stateabbrev = "NE" if statefip == 31
replace stateabbrev = "NV" if statefip == 32
replace stateabbrev = "NH" if statefip == 33
replace stateabbrev = "NJ" if statefip == 34
replace stateabbrev = "NM" if statefip == 35
replace stateabbrev = "NY" if statefip == 36
replace stateabbrev = "NC" if statefip == 37
replace stateabbrev = "ND" if statefip == 38
replace stateabbrev = "OH" if statefip == 39
replace stateabbrev = "OK" if statefip == 40
replace stateabbrev = "OR" if statefip == 41
replace stateabbrev = "PA" if statefip == 42
replace stateabbrev = "RI" if statefip == 44
replace stateabbrev = "SC" if statefip == 45
replace stateabbrev = "SD" if statefip == 46
replace stateabbrev = "TN" if statefip == 47
replace stateabbrev = "TX" if statefip == 48
replace stateabbrev = "UT" if statefip == 49
replace stateabbrev = "VT" if statefip == 50
replace stateabbrev = "VA" if statefip == 51
replace stateabbrev = "WA" if statefip == 53
replace stateabbrev = "WV" if statefip == 54
replace stateabbrev = "WI" if statefip == 55
replace stateabbrev = "WY" if statefip == 56